### ISSUE TITLE
Discord emotes = random strings

### ISSUE THREAD

**Issue by TraceLD** [DemonScythe45/polychat-client#2]
As title suggests.

![unknown](https://user-images.githubusercontent.com/46228022/57987001-2c57dd80-7a7c-11e9-82e1-d73f7b8a2aa6.png)

**Comment by 132ikl** [comment]
Strings aren't random, they're the IDs of the emojis

**Comment by TraceLD** [comment]
Still annoying and it shouldn't be like that.

**Comment by 132ikl** [comment]
@DemonScythe45 Close this issue, also please give me maintainer lol

**Comment by 132ikl** [comment]
thankies
